### ISSUE TITLE
sms.py don't work with flatpak version of kdeconnect

### ISSUE THREAD

**Issue by Marukesu** [MrMarukesu/flatpak-indicator-kdeconnect#4]
it's need more test, butt, when i try to send a sms, a error in sms.py occurs  (seeing it with the flatpak version of kdeconnect, need test with the non-flatpak version).

**Comment by b4j4** [comment]
Maybe in the latter case, the solution might be, convert sms.py to binary?

**Comment by Marukesu** [comment]
In fact it will only be necessary to change the sms.py from running kdeconnect-cli to the dbus interface directly, I have already created an issue in the repository ([#97](https://github.com/Bajoja/indicator-kdeconnect/issues/97)), if possible.

**Comment by b4j4** [comment]
It's possible to make it work with DBUS, but now i don't have time, but i will do the changes very soon
